version: '3.9'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - ./volumes/mariadb:/bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine

  redmine:
    image: docker.io/bitnami/redmine:5
    ports:
      - '80:3000'
    volumes:
      - ./volumes/redmine:/bitnami/redmine
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
      - REDMINE_DATABASE_USER=bn_redmine
      - REDMINE_DATABASE_NAME=bitnami_redmine
      - REDMINE_PASSWORD=admin@123

  mongodb:
    image: mongo:5.0.10
    volumes:
      - ./volumes/mongodb:/data/db
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://root:admin123@mongodb:27017/

  prediction_mechanism:
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../src/:/app/src
    environment:
      - MONGODB_URL=mongodb://root:admin123@mongodb:27017
      - REDMINE_URL=http://redmine:3000
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - redmine
      - mongodb