# MONGODB COLLECTIONS PROPERTIES
TB_CONFIG_KEY = "key"
TB_CONFIG_VALUE = "value"

# CONFIGURATIONS KEYS
CFG_KEY_LAST_ISSUE_DATE_TIME = "last_issue_date_time"
CFG_KEY_LAST_UPDATED_ISSUE_DATE_TIME = "last_updated_issue_date_time"

# REDMINE API PATHS
REDMINE_ISSUES_PATH = "/issues.json"

# ENVIRONMENT VARIABLES
REDMINE_URL = "REDMINE_URL"

# MISC
ISSUE_TEXT_SEPARATOR = " - "
MAX_SIMILARITIES_RETURNED = 10